[build]
builder = "nixpacks"

[deploy]
startCommand = "cd monitoreo && python manage.py migrate && gunicorn monitoreo.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"